name: test

on:
  push:
    branches:
      - runner-context

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: macOS 11
            runs-on: macos-11
          - name: macOS 12
            runs-on: macos-12
          - name: Ubuntu 22.04
            runs-on: ubuntu-22.04
    runs-on: ${{ matrix.runs-on }}
    steps:
      - run: |
          echo '${{ runner }}'
          echo '${{ runner.name }}'
          echo '${{ runner.os }}'
          echo '${{ runner.arch }}'
          echo '${{ runner.temp }}'
          echo '${{ runner.tool_cache }}'
          echo '${{ runner.debug }}'
