name: test

on:
  push:
    branches:
      - bazarr-test

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: macOS 13
            runs-on: macos-13
          - name: macOS 12
            runs-on: macos-12
          - name: macOS 11
            runs-on: macos-11
          - name: Ubuntu 22.04
            runs-on: ubuntu-22.04
            container:
              image: ghcr.io/homebrew/ubuntu22.04:master
              options: --user=linuxbrew
    name: ${{ matrix.name }}
    runs-on: ${{ matrix.runs-on }}
    container: ${{ matrix.container }}
    env:
      HOMEBREW_DEVELOPER: "1"
      HOMEBREW_NO_INSTALL_FROM_API: "1"
    steps:
      - uses: Homebrew/actions/setup-homebrew@master
      # - run: |
      #     set -x
      #     cd `brew --repo homebrew/core`
      #     git fetch origin refs/pull/139063/head:pr
      #     git checkout pr
      - run: brew cat bazarr
      - run: brew install bazarr
      - run: |
          for i in {1..50}; do
            echo "==> Test $i"
            brew test -v bazarr
            sleep 3
          done
        shell: bash
